name: QMITO000_PD_ranalysis0.1.0
channels:
  - bioconda
  - r
  - defaults
dependencies:
  - r-base=3.4.4
  - bioconductor-affycoretools=1.50.6
  - r-knitr=1.20
  - bioconductor-annotate
  - r-xml
  - bioconductor-annotationdbi=1.40.0
  - r-statmod=1.4.30
  - r-dendextend=1.8.0
  - r-ggplot2=3.0.0
  - r-gplots=3.0.1
  - bioconductor-genefilter=1.60.0
  - bioconductor-oligo=1.42.0
  - bioconductor-biostrings=2.46.0
  - bioconductor-xvector=0.18.0
  - bioconductor-iranges=2.12.0
  - bioconductor-s4vectors=0.16.0
  - bioconductor-oligoclasses=1.40.0
  - bioconductor-limma=3.34.9
  - r-rcolorbrewer
  - bioconductor-siggenes=1.52.0
  - bioconductor-multtest=2.34.0
  - bioconductor-biobase=2.38.0
  - bioconductor-biocgenerics=0.24.0
