sudo: required

language:
  - python

python:
  - "3.6"

services:
  - docker

install:
  - pip install requests
  - pip install git+https://github.com/qbicsoftware/r-lint-cli

script:
  - "ls -1 ${TRAVIS_BUILD_DIR}/projects/ | xargs -i r-lint lint {} "
  - "python ${TRAVIS_BUILD_DIR}/bin/docker.py ${TRAVIS_BUILD_DIR}/projects"
