name: QTEST000_Test_ranalysis0.1.0 
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=mro_2
  - aioeasywebdav=2.2.0=py36_0
  - aiohttp=3.5.4=py36h14c3975_0
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py36_1003
  - async-timeout=3.0.1=py_1000
  - attrs=19.1.0=py_0
  - bcrypt=3.1.4=py36h470a237_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_6
  - biopython=1.72=py36h04863e7_0
  - blas=1.0=mkl
  - boto3=1.7.84=py_0
  - botocore=1.10.84=py_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.6.16=hecc5488_0
  - cachetools=2.1.0=py_0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py36_1
  - cffi=1.12.2=py36hf0e25f4_1
  - chardet=3.0.4=py36_1003
  - configargparse=0.13.0=py_1
  - cryptography=2.5=py36hb7f436b_1
  - curl=7.61.0=h84994c4_0
  - cyrus-sasl=2.1.26=h20670df_3
  - datrie=0.7.1=py36h14c3975_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.2=py_0
  - docutils=0.14=py36_1001
  - dropbox=7.3.1=py36_0
  - entrez-direct=10.2=pl526_0
  - expat=2.2.6=he6710b0_0
  - filechunkio=1.6=py36_0
  - font-ttf-dejavu-sans-mono=2.37=h6964260_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=h7457263_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.13.0=h9420a91_0
  - fonts-anaconda=1=h8fa9717_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - ftputil=3.2=py36_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_6
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_6
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.11=py_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - google-auth=1.2.1=py_0
  - google-auth-httplib2=0.0.3=py_2
  - google-cloud-core=0.24.1=py36_0
  - google-cloud-storage=1.1.1=py36_0
  - google-resumable-media=0.0.2=py36_0
  - googleapis-common-protos=1.5.8=py_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_6
  - harfbuzz=1.8.8=hffaf4a1_0
  - httplib2=0.12.1=py36_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py36_1000
  - idna_ssl=1.1.0=py36_1000
  - intel-openmp=2019.1=144
  - jinja2=2.10=py_1
  - jmespath=0.9.3=py_1
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py36_0
  - krb5=1.16.1=hc83ff2d_6
  - libcurl=7.61.0=h1ad7b7a_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libntlm=1.4=h14c3975_2
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.7.0=hdbcaa40_1
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he6b73bb_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markupsafe=1.1.1=py36h14c3975_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36h14c3975_1
  - mkl_random=1.0.2=py36h637b7d7_2
  - mro-base=3.4.3=h1c2f66e_1
  - mro-basics=3.4.3=0
  - multidict=4.5.2=py36h14c3975_1000
  - mysql=5.7.20=hf484d3e_1001
  - ncurses=6.1=he6710b0_1
  - networkx=2.2=py_1
  - numpy=1.16.2=py36h7e9f1db_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - openjdk=8.0.152=h46b5887_1
  - openssl=1.0.2r=h14c3975_0
  - pandas=0.24.1=py36hf484d3e_0
  - pandoc=2.2.3.2=0
  - pango=1.42.4=h049681c_0
  - paramiko=2.4.2=py36_1000
  - pcre=8.42=h439df22_0
  - perl=5.26.2=h14c3975_0
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_1
  - perl-compress-raw-zlib=2.084=pl526h2d50403_0
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-digest-hmac=1.03=pl526_2
  - perl-digest-md5=2.55=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-exporter=5.72=pl526_1
  - perl-extutils-makemaker=7.34=pl526_3
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.15=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-html-parser=3.72=pl526h2d50403_4
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tree=5.07=pl526_0
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_2
  - perl-io-html=1.001=pl526_2
  - perl-io-socket-ssl=2.060=pl526_0
  - perl-libwww-perl=6.36=pl526_0
  - perl-lwp-mediatypes=6.02=pl526_3
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-mime-base64=3.15=pl526_1
  - perl-mozilla-ca=20180117=pl526_0
  - perl-net-http=6.18=pl526_0
  - perl-net-ssleay=1.85=pl526h9dad42d_0
  - perl-ntlm=1.09=pl526_3
  - perl-parent=0.236=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-storable=3.11=pl526_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-time-local=1.28=pl526_1
  - perl-try-tiny=0.30=pl526_0
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44=pl526h3a4f0e9_6
  - perl-xml-sax=1.00=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_2
  - perl-xml-simple=2.25=pl526_0
  - perl-xsloader=0.24=pl526_0
  - pip=19.0.3=py36_0
  - pixman=0.36.0=h7b6447c_0
  - prettytable=0.7.2=py_3
  - protobuf=3.7.0=py36hf484d3e_0
  - psutil=5.5.1=py36h14c3975_0
  - pyasn1=0.4.4=py_1
  - pyasn1-modules=0.0.5=py36_0
  - pycparser=2.19=py_0
  - pygraphviz=1.3.1=py36_0
  - pynacl=1.3.0=py36h14c3975_1000
  - pyrsistent=0.14.11=py36h14c3975_0
  - pysftp=0.2.9=py36_0
  - python=3.6.6=hd21baee_1003
  - python-dateutil=2.8.0=py_0
  - python-irodsclient=0.7.0=py_0
  - pytz=2018.9=py_0
  - pyyaml=3.13=py36h14c3975_1001
  - qt=5.6.3=h8bf5577_3
  - r=3.4.3=mro343_0
  - r-assertthat=0.2.0=mro343h889e2dd_0
  - r-backports=1.1.2=mro343h086d26f_0
  - r-base64enc=0.1_3=mro343h086d26f_0
  - r-bh=1.65.0_1=mro343h889e2dd_0
  - r-bindr=0.1=mro343h889e2dd_0
  - r-bindrcpp=0.2=mro343h599a50d_0
  - r-bit=1.1_12=mro343h086d26f_0
  - r-bit64=0.9_7=mro343h086d26f_0
  - r-bitops=1.0_6=mro343h086d26f_0
  - r-blob=1.1.0=mro343h889e2dd_0
  - r-boot=1.3_20=mro343_0
  - r-broom=0.4.3=mro343h889e2dd_0
  - r-catools=1.17.1=mro343h599a50d_0
  - r-cellranger=1.1.0=mro343h889e2dd_0
  - r-checkpoint=0.4.3=mro343_0
  - r-class=7.3_14=mro343_0
  - r-cli=1.0.0=mro343h889e2dd_0
  - r-cluster=2.0.6=mro343_0
  - r-codetools=0.2_15=mro343_0
  - r-config=0.2=mro343h889e2dd_0
  - r-crayon=1.3.4=mro343h889e2dd_0
  - r-curl=3.1=mro343_0
  - r-dbi=0.7=mro343h889e2dd_0
  - r-dbplyr=1.1.0=mro343h889e2dd_0
  - r-deployrrserve=9.0.0=mro343_0
  - r-digest=0.6.13=mro343h086d26f_0
  - r-doparallel=1.0.12=mro343_0
  - r-dplyr=0.7.4=mro343h599a50d_0
  - r-evaluate=0.10.1=mro343h889e2dd_0
  - r-forcats=0.2.0=mro343h889e2dd_0
  - r-foreach=1.4.5=mro343_0
  - r-foreign=0.8_69=mro343_0
  - r-glue=1.2.0=mro343h086d26f_0
  - r-haven=1.1.0=mro343h599a50d_0
  - r-highr=0.6=mro343h889e2dd_0
  - r-hms=0.4.0=mro343h889e2dd_0
  - r-htmltools=0.3.6=mro343h599a50d_0
  - r-htmlwidgets=0.9=mro343h889e2dd_0
  - r-httpuv=1.3.5=mro343h599a50d_0
  - r-httr=1.3.1=mro343h889e2dd_0
  - r-iterators=1.0.9=mro343_0
  - r-jsonlite=1.5=mro343_0
  - r-kernsmooth=2.23_15=mro343_0
  - r-knitr=1.18=mro343h889e2dd_0
  - r-lattice=0.20_35=mro343_0
  - r-lazyeval=0.2.1=mro343h086d26f_0
  - r-magrittr=1.5=mro343h889e2dd_0
  - r-markdown=0.8=mro343h086d26f_0
  - r-mass=7.3_47=mro343_0
  - r-matrix=1.2_12=mro343_0
  - r-mgcv=1.8_22=mro343_0
  - r-microsoftr=3.4.3.0097=mro343_0
  - r-mime=0.5=mro343h086d26f_0
  - r-miniui=0.1.1=mro343h889e2dd_0
  - r-mnormt=1.5_5=mro343h4829c52_0
  - r-mongolite=1.4=mro343h086d26f_0
  - r-nlme=3.1_131=mro343_0
  - r-nnet=7.3_12=mro343_0
  - r-odbc=1.1.3=mro343h599a50d_0
  - r-openssl=0.9.9=mro343h086d26f_0
  - r-packrat=0.4.8_1=mro343h889e2dd_0
  - r-pillar=1.0.1=mro343h889e2dd_0
  - r-pkgconfig=2.0.1=mro343h889e2dd_0
  - r-pki=0.1_5.1=mro343h086d26f_0
  - r-plogr=0.1_1=mro343h889e2dd_0
  - r-plyr=1.8.4=mro343h599a50d_0
  - r-png=0.1_7=mro343_0
  - r-profvis=0.3.4=mro343h086d26f_0
  - r-psych=1.7.8=mro343h889e2dd_0
  - r-purrr=0.2.4=mro343h086d26f_0
  - r-r6=2.2.2=mro343_0
  - r-rappdirs=0.3.1=mro343h086d26f_0
  - r-rcpp=0.12.14=mro343h599a50d_0
  - r-rcurl=1.95_4.9=mro343h086d26f_0
  - r-readr=1.1.1=mro343h599a50d_0
  - r-readxl=1.0.0=mro343h599a50d_0
  - r-recommended=3.4.3=mro343_0
  - r-rematch=1.0.1=mro343h889e2dd_0
  - r-reshape2=1.4.3=mro343h599a50d_0
  - r-revoioq=8.0.9=mro343_0
  - r-revomods=11.0.0=mro343_0
  - r-revoutilsmath=10.0.1=mro343_0
  - r-rjava=0.9_9=mro343h086d26f_0
  - r-rjdbc=0.2_5=mro343h889e2dd_0
  - r-rjsonio=1.3_0=mro343h599a50d_0
  - r-rlang=0.1.6=mro343h086d26f_0
  - r-rmarkdown=1.8=mro343h889e2dd_0
  - r-rmysql=0.10.13=mro343h086d26f_0
  - r-rpart=4.1_11=mro343_0
  - r-rprojroot=1.3_1=mro343h889e2dd_0
  - r-rsconnect=0.8.5=mro343h889e2dd_0
  - r-rstudioapi=0.7=mro343h889e2dd_0
  - r-runit=0.4.26=mro343_0
  - r-shiny=1.0.5=mro343h889e2dd_0
  - r-sourcetools=0.1.6=mro343h599a50d_0
  - r-sparklyr=0.6.4=mro343h889e2dd_0
  - r-spatial=7.3_11=mro343_0
  - r-stringi=1.1.6=mro343h599a50d_0
  - r-stringr=1.2.0=mro343h889e2dd_0
  - r-survival=2.41_3=mro343_0
  - r-tibble=1.4.1=mro343h086d26f_0
  - r-tidyr=0.7.2=mro343h599a50d_0
  - r-tidyselect=0.2.3=mro343h599a50d_0
  - r-utf8=1.1.2=mro343h086d26f_0
  - r-withr=2.1.1=mro343h889e2dd_0
  - r-xml2=1.1.1=mro343h599a50d_0
  - r-xtable=1.8_2=mro343h889e2dd_0
  - r-yaml=2.1.16=mro343h086d26f_0
  - ratelimiter=1.2.0=py36_1000
  - readline=7.0=hf8c457e_1001
  - requests=2.13.0=py36_0
  - rsa=3.1.4=py36_0
  - rstudio=1.1.456=h6bb024c_1
  - s3transfer=0.1.13=py36_1001
  - setuptools=40.8.0=py36_0
  - six=1.12.0=py36_1000
  - smmap2=2.0.5=py_0
  - snakemake=5.4.2=0
  - snakemake-minimal=5.4.2=py_1
  - snpeff=4.3.1t=2
  - snpsift=4.3.1t=1
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - typing_extensions=3.7.2=py36_1000
  - unixodbc=2.3.7=h14c3975_0
  - urllib3=1.12=py36_0
  - wheel=0.33.1=py36_0
  - wrapt=1.11.1=py36h14c3975_0
  - xmlrunner=1.7.7=py_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h14c3975_1001
  - yarl=1.3.0=py36h14c3975_1000
  - zlib=1.2.11=h7b6447c_3

